# Generated by Django 4.2.1 on 2023-05-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatnamehistory',
            name='chat_creator',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
