# Generated by Django 4.2.1 on 2023-05-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_data', '0002_chatnamehistory_chat_creator_delete_chathistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageHistory',
        ),
    ]
