# Generated by Django 4.2.1 on 2023-05-24 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_data', '0003_delete_messagehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=200)),
                ('time_sending', models.DateTimeField(auto_now_add=True)),
                ('user_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
