# Generated by Django 4.2.1 on 2023-05-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_data', '0004_messagehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageHistory',
        ),
    ]
