# Generated by Django 4.2.1 on 2023-05-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_data', '0006_messagehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagehistory',
            name='user_message',
        ),
    ]
