# Generated by Django 4.2.1 on 2023-05-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_data', '0007_remove_messagehistory_user_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatNameHistory',
        ),
        migrations.DeleteModel(
            name='MessageHistory',
        ),
    ]
