# Generated by Django 4.2.1 on 2023-05-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_data', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatnamehistory',
            name='chat_name',
            field=models.CharField(max_length=200),
        ),
    ]
