# Generated by Django 4.2.1 on 2023-05-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_data', '0010_alter_chatnamehistory_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='user_name',
            field=models.CharField(max_length=200),
        ),
    ]
