# Generated by Django 4.2.1 on 2023-05-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_data', '0011_alter_messagehistory_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagehistory',
            name='user_name',
        ),
    ]
