# Generated by Django 4.2.1 on 2023-05-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_data', '0013_alter_chatnamehistory_chat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagehistory',
            name='time_sending',
        ),
    ]
